name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # ou sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy base-project \
            --source . \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
