name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Save service account key
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > ${{ github.workspace }}/gcloud-key.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcloud-key.json
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth activate-service-account --key-file=${{ github.workspace }}/gcloud-key.json
          gcloud run deploy base-project \
            --source . \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
